# Generated by Django 5.2.17 on 2026-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaneException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=10)),
                ('loads', models.IntegerField()),
                ('current_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('var_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('var_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence', models.CharField(max_length=20)),
                ('impact', models.CharField(max_length=20)),
                ('adjustment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_adjusted_target', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_date', models.DateField(blank=True, null=True)),
                ('adjusted_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('avg_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variance_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loads', models.IntegerField()),
                ('trend_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PricingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
