# Generated by Django 5.2.17 on 2026-08-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laneexception',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.organization'),
        ),
        migrations.AddField(
            model_name='marketsummary',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_summaries', to='customers.organization'),
        ),
        migrations.AddField(
            model_name='pricingadjustment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_adjustments', to='customers.organization'),
        ),
        migrations.AddConstraint(
            model_name='pricingadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('change_percent__gte', -100)), name='pricing_change_percent_min'),
        ),
    ]
