# Generated by Django 5.2.17 on 2026-08-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRateLane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_id', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=2)),
                ('raw_origin', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=2)),
                ('raw_destination', models.CharField(max_length=200)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('miles', models.IntegerField()),
                ('status', models.CharField(choices=[('AWARDED', 'AWARDED'), ('BACKUP', 'BACKUP'), ('SPOT', 'SPOT')], default='AWARDED', max_length=20)),
                ('active_state', models.CharField(choices=[('Active', 'Active'), ('Future', 'Future'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('fuel_surcharge_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_billing', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
