# Generated by Django 5.2.17 on 2026-08-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerratelane',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_lanes', to='customers.organization'),
        ),
        migrations.AddConstraint(
            model_name='customerratelane',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate__gte', 0)), name='rates_base_rate_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerratelane',
            constraint=models.CheckConstraint(condition=models.Q(('miles__gte', 0)), name='rates_miles_non_negative'),
        ),
    ]
